### ISSUE TITLE
can we make a version for 1.34.2?

### ISSUE THREAD

**Issue by RuoChennn** [qqrz997/KeepMyOverridesPls#1]

**Comment by qqrz997** [comment]
out of curiosity why are you using 1.34.2? i presume it's because you're using noodle extensions, but feel free to correct me.

i'm not going to contribute to older versions because i don't want people to feel like they have to downgrade all of the time because of the extra effort it takes to do

**Comment by RuoChennn** [comment]
1.37mods is not enough to update , until it complete i will stay in old version
